name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    uses: josh-development/.github/.github/workflows/lint.yml@main

  building:
    uses: josh-development/.github/.github/workflows/build.yml@main

  docs:
    uses: josh-development/.github/.github/workflows/docs.yml@main
